# Generated by Django 3.2.4 on 2021-07-13 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ProfileSite', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MovieSections', models.CharField(max_length=200, verbose_name='أقسام المسابقة')),
                ('is_active', models.BooleanField(default=False, verbose_name='الحالة')),
            ],
            options={
                'verbose_name': 'أقسام المسابقة',
                'verbose_name_plural': 'أقسام المسابقة',
            },
        ),
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Section', models.CharField(max_length=200, verbose_name='الموسم')),
                ('is_active', models.BooleanField(default=False, verbose_name='الحالة')),
            ],
            options={
                'verbose_name': 'الموسم',
                'verbose_name_plural': 'الموسم',
            },
        ),
        migrations.CreateModel(
            name='Stages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stage', models.CharField(max_length=50, verbose_name='مراحل المسابقة')),
                ('is_active', models.BooleanField(default=False, verbose_name='الحالة')),
                ('Section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='VideoApp.sections', verbose_name='الموسم')),
            ],
            options={
                'verbose_name': 'مراحل المسابقة',
                'verbose_name_plural': 'مراحل المسابقة',
            },
        ),
        migrations.CreateModel(
            name='VideoFiles',
            fields=[
                ('title', models.CharField(default='فيديو١', max_length=200, verbose_name='العنوان')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('video', models.FileField(upload_to='VideoApp/Video/%Y%/%m/%d')),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(verbose_name='وصف الفيديو')),
                ('visibility', models.BooleanField(choices=[(False, 'خاص'), (True, 'عام')], verbose_name='حالة الفيديو')),
                ('thumbnail', models.ImageField(upload_to='VideoApp/Img/%Y%/%m/%d', verbose_name='صورة الفيديو')),
                ('is_active', models.BooleanField(default=True, verbose_name='موافقة نشر')),
                ('is_admin', models.BooleanField(default=False, verbose_name='المدير')),
                ('is_staff', models.BooleanField(default=False, verbose_name='التميز')),
                ('MovieSections', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='VideoApp.moviesection', verbose_name='قسم المسابقة')),
                ('Section', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='VideoApp.sections', verbose_name='الموسم')),
                ('Specialty', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ProfileSite.specialty', verbose_name='التخصص')),
                ('SpecialtyType', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ProfileSite.specialtytype', verbose_name='نوع التخصص')),
                ('Stages', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='VideoApp.stages', verbose_name='مراحل المسابقة')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProfileSite.profile')),
                ('dislikes', models.ManyToManyField(related_name='video_disliked', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(related_name='video_loved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ملف التحمل',
                'verbose_name_plural': 'ملف التحمل',
            },
        ),
        migrations.CreateModel(
            name='ViewCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=50, verbose_name='اي بي')),
                ('session', models.CharField(max_length=50, verbose_name='مشاهدة')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_count', to='VideoApp.videofiles', verbose_name='الفيديو')),
            ],
            options={
                'verbose_name': 'المشاهدات',
                'verbose_name_plural': 'المشاهدات',
            },
        ),
        migrations.CreateModel(
            name='VideoComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProfileSite.profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='VideoApp.videofiles')),
            ],
            options={
                'verbose_name': 'تعليقات',
                'verbose_name_plural': 'تعليقات',
            },
        ),
    ]
