# Generated by Django 3.2.4 on 2021-07-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0002_auto_20210721_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='موافقة نشر'),
        ),
    ]
