# Generated by Django 3.2.4 on 2021-07-26 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0003_alter_articles_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='updatedArticles',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
    ]
