# Generated by Django 3.2.4 on 2021-07-13 16:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ProfileSite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('YouTubeType', models.CharField(max_length=50, verbose_name='قسم الفيديو')),
            ],
            options={
                'verbose_name': 'أقسام الفيديوهات',
                'verbose_name_plural': 'أقسام الفيديوهات',
            },
        ),
        migrations.CreateModel(
            name='YouTube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('linke', models.TextField(verbose_name='رابط الفيديو')),
                ('content', models.TextField(verbose_name='وصف الفيديو')),
                ('image', models.ImageField(blank=True, upload_to='youTube/%Y%/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])], verbose_name='رفع الصورة')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تتاريخ التحديث')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التتسجيل')),
                ('is_active', models.BooleanField(default=True, verbose_name='موافقة نشر')),
                ('is_admin', models.BooleanField(default=False, verbose_name='الادارة')),
                ('is_staff', models.BooleanField(default=False, verbose_name='التميز')),
                ('YouTubeType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CinamaMedia.youtubetypes', verbose_name='نوع التخصص')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='YouTubs', to='ProfileSite.profile', verbose_name='أسم المستخدم')),
            ],
            options={
                'verbose_name': 'الفيديوهات',
                'verbose_name_plural': 'الفيديوهات',
            },
        ),
    ]
