# Generated by Django 3.2.4 on 2021-07-21 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CinamaMedia', '0002_auto_20210721_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youtube',
            name='is_Site_1',
        ),
        migrations.RemoveField(
            model_name='youtube',
            name='is_Site_2',
        ),
        migrations.RemoveField(
            model_name='youtube',
            name='is_Site_3',
        ),
        migrations.RemoveField(
            model_name='youtube',
            name='is_Site_4',
        ),
        migrations.AddField(
            model_name='youtubetypes',
            name='is_Site_1',
            field=models.BooleanField(default=True, verbose_name='قسم الاول'),
        ),
        migrations.AddField(
            model_name='youtubetypes',
            name='is_Site_2',
            field=models.BooleanField(default=False, verbose_name='قسم الثاني'),
        ),
        migrations.AddField(
            model_name='youtubetypes',
            name='is_Site_3',
            field=models.BooleanField(default=False, verbose_name='قسم الثالث'),
        ),
        migrations.AddField(
            model_name='youtubetypes',
            name='is_Site_4',
            field=models.BooleanField(default=True, verbose_name='قسم الرابع'),
        ),
    ]
