# Generated by Django 3.2.4 on 2021-07-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CinamaMedia', '0004_youtubetypes_is_site_5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubetypes',
            name='is_Site_1',
            field=models.BooleanField(default=False, verbose_name='قسم الاول'),
        ),
        migrations.AlterField(
            model_name='youtubetypes',
            name='is_Site_4',
            field=models.BooleanField(default=False, verbose_name='قسم الرابع'),
        ),
        migrations.AlterField(
            model_name='youtubetypes',
            name='is_Site_5',
            field=models.BooleanField(default=False, verbose_name='قسم الخامس'),
        ),
    ]
