# Generated by Django 3.2.4 on 2021-07-22 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CinamaMedia', '0006_lectures_lecturestypes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lectures',
            name='Date',
            field=models.DateTimeField(verbose_name='تاريخ المحاضرة'),
        ),
        migrations.AlterField(
            model_name='lectures',
            name='Time',
            field=models.TimeField(verbose_name='وقت المحاضرة'),
        ),
    ]
