# Generated by Django 3.2.4 on 2021-07-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CinamaMedia', '0007_auto_20210722_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='CinamaMedias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('Facebook', models.CharField(blank=True, max_length=500, null=True, verbose_name='الفيس بوك')),
                ('Instagram', models.CharField(blank=True, max_length=500, null=True, verbose_name='انستقرام')),
                ('Twitter', models.CharField(blank=True, max_length=500, null=True, verbose_name='تويتر')),
                ('Snapchat', models.CharField(blank=True, max_length=500, null=True, verbose_name='سناب شات')),
                ('YouTube', models.CharField(blank=True, max_length=500, null=True, verbose_name='اليوتيوب')),
            ],
            options={
                'verbose_name': 'موقع تتواصل المهرجان',
                'verbose_name_plural': 'موقع تتواصل المهرجان',
            },
        ),
    ]
