# Generated by Django 3.2.4 on 2021-07-13 16:29

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ProfileSite', '0001_initial'),
        ('VideoApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JudgementComitys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True, verbose_name='الاسم')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='من انا')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التتسجيل')),
                ('is_log', models.BooleanField(default=True, verbose_name='تسجيل')),
                ('is_approval', models.BooleanField(default=True, verbose_name='موافقة')),
                ('is_active', models.BooleanField(default=True, verbose_name='موافقة نشر')),
                ('is_admin', models.BooleanField(default=False, verbose_name='لجنة التحكيم')),
                ('is_staff', models.BooleanField(default=False, verbose_name='انتهاء')),
                ('JudgementComity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProfileSite.profile', verbose_name='لجنة التحكيم')),
                ('MovieSections', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VideoApp.moviesection', verbose_name='قسم المسابقة')),
                ('Section', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='VideoApp.sections', verbose_name='الموسم')),
                ('Stages', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VideoApp.stages', verbose_name='مراحل المسابقة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='أسم المستخدم')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='VideoApp.videofiles', verbose_name='الفيديو')),
            ],
            options={
                'verbose_name': 'تحكيم المتسابقين',
                'verbose_name_plural': 'تحكيم المتسابقين',
            },
        ),
    ]
