# Generated by Django 3.2.4 on 2021-07-14 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VideoApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Competitions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JudgementRacer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True, verbose_name='الاسم')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التتسجيل')),
                ('is_log', models.BooleanField(default=True, verbose_name='تسجيل')),
                ('is_approval', models.BooleanField(default=True, verbose_name='موافقة')),
                ('is_active', models.BooleanField(default=True, verbose_name='موافقة نشر')),
                ('is_admin', models.BooleanField(default=False, verbose_name='لجنة التحكيم')),
                ('is_staff', models.BooleanField(default=False, verbose_name='انتهاء')),
                ('JudgementComity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Competitions.judgementcomitys', verbose_name='لجنة التحكيم')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='أسم المستخدم')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='VideoApp.videofiles', verbose_name='الفيديو')),
            ],
            options={
                'verbose_name': 'المتسابقين',
                'verbose_name_plural': 'المتسابقين',
            },
        ),
    ]
