# Generated by Django 3.2.4 on 2021-07-13 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialtyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SpecialtyType', models.CharField(max_length=50, verbose_name='نوع التخصص')),
                ('is_active', models.BooleanField(default=False, verbose_name='الحالة')),
            ],
            options={
                'verbose_name': 'نوع التخصص',
                'verbose_name_plural': 'نوع تخصص',
            },
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('State', models.CharField(max_length=50, verbose_name='الدولة')),
                ('is_active', models.BooleanField(default=False, verbose_name='الحالة')),
            ],
            options={
                'verbose_name': 'الدول',
                'verbose_name_plural': 'الدول',
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Specialty', models.CharField(max_length=50, verbose_name='نوع التخصص')),
                ('is_active', models.BooleanField(default=False, verbose_name='الحالة')),
                ('SpecialtyType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ProfileSite.specialtytype', verbose_name='التخصص')),
            ],
            options={
                'verbose_name': 'التخصص',
                'verbose_name_plural': 'التخصص',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(blank=True, max_length=200, null=True, verbose_name='الاسم الكامل')),
                ('age', models.BooleanField(choices=[(False, 'لا ـ No'), (True, 'نعم ـ Yes')], help_text='greater than 18', verbose_name='فئة أكبر من 18')),
                ('DateOfBirth', models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد')),
                ('gender', models.BooleanField(choices=[(False, 'ذكر ـ man'), (True, 'انثى ـ female')], help_text='What is the gender?', verbose_name='نوع الجنس')),
                ('Phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم الجوال')),
                ('Profile_Art', models.ImageField(default='default_art.jpg', upload_to='Profile_Art/%Y%/%m/%d/', verbose_name='صورة ويب')),
                ('Profile_Icon', models.ImageField(default='default_icon.png', upload_to='Profile_Icon/%Y/%m/%d/', verbose_name='صورة المستخدم')),
                ('description', models.TextField(blank=True, null=True, verbose_name='نبدا عنك')),
                ('address', models.TextField(blank=True, null=True, verbose_name='عنوان الاقامة')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='id')),
                ('follower', models.IntegerField(default=0)),
                ('following', models.IntegerField(default=0)),
                ('emaiAddress', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الكتروني')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='تاريخ الدخول')),
                ('is_active', models.BooleanField(default=True, verbose_name='المستخدم')),
                ('is_subcriber', models.BooleanField(default=False, verbose_name='مشترك')),
                ('is_supersubcriber', models.BooleanField(default=False, verbose_name='للجنة التحكيم')),
                ('is_admin', models.BooleanField(default=False, verbose_name='المدير')),
                ('is_staff', models.BooleanField(default=False, verbose_name='التميز')),
                ('is_star', models.BooleanField(default=False, verbose_name='نجمة')),
                ('Facebook', models.CharField(blank=True, max_length=500, null=True, verbose_name='الفيس بوك')),
                ('Instagram', models.CharField(blank=True, max_length=500, null=True, verbose_name='انستقرام')),
                ('Twitter', models.CharField(blank=True, max_length=500, null=True, verbose_name='تويتر')),
                ('Snapchat', models.CharField(blank=True, max_length=500, null=True, verbose_name='سناب شات')),
                ('YouTube', models.CharField(blank=True, max_length=500, null=True, verbose_name='اليوتيوب')),
                ('Skype', models.CharField(blank=True, max_length=500, null=True, verbose_name='سكاي بي')),
                ('Zoom', models.CharField(blank=True, max_length=500, null=True, verbose_name='زوم')),
                ('Specialty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ProfileSite.specialty', verbose_name='التخصص')),
                ('SpecialtyType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ProfileSite.specialtytype', verbose_name='نوع التخصص')),
                ('State', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ProfileSite.states', verbose_name='الدولة')),
                ('subcribers', models.ManyToManyField(blank=True, related_name='subscribers', to=settings.AUTH_USER_MODEL, verbose_name='المشتركين')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='أسم المستخدم')),
            ],
            options={
                'verbose_name': 'الملف الشخصي',
                'verbose_name_plural': 'الملف الشخصي',
            },
        ),
    ]
