# Generated by Django 3.2.4 on 2021-07-28 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileSite', '0002_auto_20210728_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialty',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='specialtytype',
            name='is_Site_1',
            field=models.BooleanField(default=False, verbose_name='الهيئة العليا'),
        ),
        migrations.AlterField(
            model_name='specialtytype',
            name='is_Site_2',
            field=models.BooleanField(default=False, verbose_name='الادارة'),
        ),
        migrations.AlterField(
            model_name='specialtytype',
            name='is_Site_3',
            field=models.BooleanField(default=False, verbose_name='لجنة التحكيم'),
        ),
        migrations.AlterField(
            model_name='specialtytype',
            name='is_Site_4',
            field=models.BooleanField(default=False, verbose_name='المشتركين'),
        ),
        migrations.AlterField(
            model_name='specialtytype',
            name='is_Site_5',
            field=models.BooleanField(default=False, verbose_name='أعضاء التميز'),
        ),
    ]
