# Generated by Django 3.2.4 on 2021-07-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileSite', '0003_auto_20210728_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_Articles',
            field=models.BooleanField(default=False, verbose_name='مقالات'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_Media',
            field=models.BooleanField(default=False, verbose_name='مواقع تواصل الاجتماعي'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_Posts',
            field=models.BooleanField(default=False, verbose_name='منشورات'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_Video',
            field=models.BooleanField(default=False, verbose_name='فيديوهات'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_YouTube',
            field=models.BooleanField(default=False, verbose_name='اليوتيوب'),
        ),
    ]
